//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Config.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Config.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap bb {
            get {
                object obj = ResourceManager.GetObject("bb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bk {
            get {
                object obj = ResourceManager.GetObject("bk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bn {
            get {
                object obj = ResourceManager.GetObject("bn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bp {
            get {
                object obj = ResourceManager.GetObject("bp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bq {
            get {
                object obj = ResourceManager.GetObject("bq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap br {
            get {
                object obj = ResourceManager.GetObject("br", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =Game 1
        ///!a2-a3
        ///!d5-d4
        ///!b2-b3
        ///!c6-d5
        ///!a3-a4
        ///!d6-e4
        ///!c2-c3
        ///!c5-c4
        ///!d2-d3
        ///!b5-b4
        ///!d1-c2
        ///!b6-c6
        ///!c1-d2
        ///!d5-d6
        ///!c3-b4
        ///!c6-b5
        ///!d3-e4
        ///!d6-c5
        ///!b1-c3
        ///!c5-b4
        ///!d2-c1
        ///!e6-b6
        ///!c2-b2
        ///!b5-a4
        ///!b2-b1
        ///!a4-b3
        ///!b1-d3
        ///!b3-c3
        ///!e1-d2
        ///!c3-a1
        ///!d3-c3
        ///!a1-b1
        ///!c3-b4
        ///!a5-b4
        ///!c1-b2
        ///!c4-c3
        ///!b2-a1
        ///!a6-b5
        ///!d2-c3
        ///!b1-c2
        ///!c3-b3
        ///!c2-a2
        ///!b3-a4
        ///!a2-c2
        ///!a4-b4
        ///!c2-c4
        ///!b4-c3
        ///!b6-c6
        ///!c3-b3
        ///!c6-b6
        ///!b3-b2
        ///!c4-b3
        ///!b2-c3
        ///!b3-a2
        ///!c3-c2
        ///!a2-a6
        ///!a1-b2
        ///!a6-a1
        ///!b2-b3
        ///!b5-c5
        ///!b3-c3
        ///!c5-b4
        ///!c3-b2        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string testdata {
            get {
                return ResourceManager.GetString("testdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =Game 1
        ///!a2-a3
        ///!d6-c4
        ///!c2-c3
        ///!a5-a4
        ///!a1-a2
        ///!d5-d4
        ///!d1-b3
        ///!c6-d5
        ///!d2-d3
        ///!c4-e3
        ///!b3-c2
        ///!a6-a5
        ///!a2-a1
        ///!b6-c6
        ///!b2-b3
        ///!a5-a6
        ///!c3-c4
        ///!c6-d6
        ///!c4-b5
        ///!d5-b3
        ///!e1-d2
        ///!c5-c4
        ///!a1-a2
        ///!b3-b4
        ///!d2-c3
        ///!b4-b3
        ///!b5-a6
        ///=Game 2
        ///!c2-c3
        ///!d6-c4
        ///!d2-d3
        ///!c4-d2
        ///!e2-e3
        ///!d2-b3
        ///!d1-b3
        ///!c5-c4
        ///!b3-a3
        ///!b6-c5
        ///!a3-b4
        ///!c5-e3
        ///!b4-a5
        ///!e3-d3
        ///!b1-d2
        ///!d3-e4
        ///!a5-a3
        ///!a6-b6
        ///!a3-b4
        ///!c6-d6
        ///!a1-b1
        ///!e4-e1
        ///=Game 3
        ///!b1-a3
        ///!d6-e4
        ///!d2-d3
        ///!a5-a4
        ///!a3-c4
        ///!b6-a5
        ///!c4-e3
        ///!b5-b4
        ///!c1-d2
        ///!a6-b6
        ///!d2-b4
        ///!c5-b [rest of string was truncated]&quot;;.
        /// </summary>
        public static string testdataalsobad {
            get {
                return ResourceManager.GetString("testdataalsobad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =Game 1
        ///!c5-c4
        ///!b2-b3
        ///!b6-e3
        ///!c1-a3
        ///!e5-e4
        ///!a3-c1
        ///!c4-c3
        ///!c1-b2
        ///!e3-d3
        ///!b3-b4
        ///!d3-c2
        ///!e2-e3
        ///!d6-b2
        ///!d2-d3
        ///!c6-c5
        ///!d1-c2
        ///!e6-e5
        ///!b4-c5
        ///!e5-e6
        ///!c5-d6
        ///!b2-d1
        ///!c2-b2
        ///!b5-b4
        ///!d3-d4
        ///!c3-b2
        ///!d6-b6
        ///!e6-c6
        ///!b6-c6
        ///!a6-c4
        ///!c6-d6
        ///!c4-a2
        ///!d6-e5
        ///!a2-b3
        ///!e5-e6
        ///!b3-c4
        ///!e6-b6
        ///!c4-d4
        ///!b6-b5
        ///!d4-c4
        ///!b5-a4
        ///!d5-d4
        ///!a4-c2
        ///!c4-c2
        ///!e3-d4
        ///!c2-d3
        ///!a1-a4
        ///!d3-c4
        ///!a4-a2
        ///!c4-b3
        ///!a2-a5
        ///!b3-d5
        ///!a5-a6
        ///!d5-a5
        ///!d4-d5
        ///!a5-a6
        ///!d5-c6
        ///!b4-b3
        ///!c6-c3
        ///!a6-e2
        ///!c3-e3
        ///!e2-d2
        ///!e3-c3
        ///!e4-e3        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string testdatabad {
            get {
                return ResourceManager.GetString("testdatabad", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap wb {
            get {
                object obj = ResourceManager.GetObject("wb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap wk {
            get {
                object obj = ResourceManager.GetObject("wk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap wn {
            get {
                object obj = ResourceManager.GetObject("wn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap wp {
            get {
                object obj = ResourceManager.GetObject("wp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap wq {
            get {
                object obj = ResourceManager.GetObject("wq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap wr {
            get {
                object obj = ResourceManager.GetObject("wr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
